### ISSUE TITLE
Library won't import to project with minSDK 19

### ISSUE THREAD

**Issue by moozgoos** [saiakhil8/ConsentDialog#1]
Library won't import to project with minSDK 19. Can you change it?

**Comment by saiakhil8** [comment]
Sure..will change minSdk version...
In the mean time u can also add <uses-sdk tools:ignore:"libname"> to manifest..and it will work without any issue..
Anyway in Few hours will update library.

**Comment by moozgoos** [comment]
Great, thank you :-)

Wysłane z iPhone'a

**Comment by saiakhil8** [comment]
@moozgoos New Version released..Now reduced minsdkVersion

**Comment by saiakhil8** [comment]
**closing the issue**
